version: 2.1

executors:
  foo:
    docker:
      - image: cimg/base:2021.04
    resource_class: medium+

  ubuntu:
    machine:
      image: ubuntu-2004:202010-01

jobs:
  test:
    executor: ubuntu
    steps:
      - run: echo "Hello, world!"

workflows:
  version: 2.1
  test:
    jobs:
      - test:
          filters:
            branches:
              only: machine
      
