version: 2.1

executors:
  runner:
    machine: true
    resource_class: domparfitt/test

jobs:
  runner-test-2:
    executor: runner
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/foo.txt

  large-cache:
    executor: runner
    steps:
      - run: mkfile -n 1G large_file
      - save_cache:
          key: foo.txt
          paths:
            - large_file
      - restore_cache:
          key: foo.txt

workflows:
  version: 2.1

  runner-test:
    jobs:
      - large-cache:
          filters:
            branches:
              only: runner
