version: 2.1

executors:
  foo:
    docker:
      - image: cimg/base:2021.04
    resource_class: medium+

jobs:
  test:
    executor: foo
    steps:
      - run: echo "Hello, world!"

  runner-test:
    machine: true
    resource_class: domparfitt/test
    steps:
      - checkout
      - run: echo "Hi I'm on Runners!"

workflows:
  version: 2.1
  test:
    jobs:
      - test:
          filters:
            branches:
              only: master

  runner-test:
    jobs:
      - runner-test:
          filters:
            branches:
              only: runner
      