version: 2.1

executors:
  foo:
    docker:
      - image: cimg/base:2021.04
    resource_class: medium+
  runner:
    machine: true
    resource_class: domparfitt/test

jobs:
  test:
    executor: foo
    steps:
      - run: echo "Hello, world!"

  runner-test:
    executor: foo
    # machine: true
    # resource_class: domparfitt/test
    steps:
      - checkout
      - run: cat foo.txt
      - run: echo "Hi I'm on Runner!"
      - persist_to_workspace:
          root: .
          paths:
            - 'foo.txt'

  runner-test-2:
    executor: foo
    steps:
      - attach_workspace:
          at: $FOO
      - run: cat /tmp/workspace/foo.txt

  cache-save:
    executor: foo
    parallelism: 4
    steps:
      - run: echo "Hello, world" > foo.txt
      - save_cache:
          paths:
            - 'foo.txt'
          key: foo

  cache-restore:
    executor: foo
    parallelism: 4
    steps:
      - restore_cache:
          key: foo
      - run: cat foo.txt

workflows:
  version: 2.1
  test:
    jobs:
      - test:
          filters:
            branches:
              only: master

  runner-test:
    jobs:
      - runner-test:
          filters:
            branches:
              only: cache-test
      - runner-test-2:
          requires:
            - runner-test
          filters:
            branches:
              only: cache-test

  cache-test:
    jobs:
      - cache-save:
          filters:
            branches:
              only: cache-test
      - cache-restore:
          requires:
            - cache-save
          filters:
            branches:
              only: cache-test
